return function(c, hl)
	hl("CmpItemAbbr", { fg = c.on_surface })
	hl("CmpItemAbbrDeprecated", { fg = c.outline, strikethrough = true })
	hl("CmpItemAbbrMatch", { fg = c.primary, bold = true })
	hl("CmpItemAbbrMatchFuzzy", { fg = c.primary, bold = true })
	hl("CmpItemKind", { fg = c.on_surface_variant })
	hl("CmpItemMenu", { fg = c.outline })

	-- Custom highlight groups for each type of completions
	hl("CmpItemKindText", { fg = c.on_surface_variant })
	hl("CmpItemKindMethod", { fg = c.secondary })
	hl("CmpItemKindFunction", { fg = c.secondary })
	hl("CmpItemKindConstructor", { fg = c.primary })
	hl("CmpItemKindField", { fg = c.tertiary })
	hl("CmpItemKindVariable", { fg = c.on_surface })
	hl("CmpItemKindClass", { fg = c.secondary_fixed_dim })
	hl("CmpItemKindInterface", { fg = c.primary })
	hl("CmpItemKindModule", { fg = c.on_surface_variant })
	hl("CmpItemKindProperty", { fg = c.tertiary })
	hl("CmpItemKindUnit", { fg = c.secondary })
	hl("CmpItemKindValue", { fg = c.secondary })
	hl("CmpItemKindEnum", { fg = c.secondary_fixed_dim })
	hl("CmpItemKindKeyword", { fg = c.primary, bold = true })
	hl("CmpItemKindSnippet", { fg = c.tertiary })
	hl("CmpItemKindColor", { fg = c.tertiary })
	hl("CmpItemKindFile", { fg = c.primary })
	hl("CmpItemKindReference", { fg = c.secondary })
	hl("CmpItemKindFolder", { fg = c.primary })
	hl("CmpItemKindEnumMember", { fg = c.primary_fixed_dim })
	hl("CmpItemKindConstant", { fg = c.primary_fixed_dim, bold = true })
	hl("CmpItemKindStruct", { fg = c.secondary_fixed_dim })
	hl("CmpItemKindEvent", { fg = c.secondary })
	hl("CmpItemKindOperator", { fg = c.inverse_primary })
	hl("CmpItemKindTypeParameter", { fg = c.secondary_fixed_dim })
end
